//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProjectOOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client:User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
       
    
        public int C_ID { get; set; }
        //public string FirstName { get; set; }
        //public string LastName { get; set; }
        //public string Phone { get; set; }
        //public string Email { get; set; }
        //public string Password { get; set; }
        //public string Address { get; set; }
        //public string City { get; set; }
        //public string ZIPCode { get; set; }
        public Code Code;
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes { get; set; }


        public void Clientt(int C_ID,  Code Code)
        {
            this.C_ID = C_ID;
            this.Code = Code;
        }
        //public void display()
        //{
        //    Console.WriteLine(C_ID+ " " + Code.month + " " + Code.coID +" "+ Code.code1);
        //}
    }

}
