//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProjectOOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public int coID { get; set; }
        public string month { get; set; }
        public int C_ID { get; set; }
        public string code1 { get; set; }
    
        public virtual Client Client { get; set; }

        public void Codee(int coID, string month,string code1)
        {
            this.coID = coID;
            this.month = month;
            this.code1 = code1;
        }
    }
}
