//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProjectOOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee:User
    {
        public int E_ID { get; set; }
        //public string FirstName { get; set; }
        //public string LastName { get; set; }
        //public string Phone { get; set; }
        //public string Password { get; set; }
        //public string Address { get; set; }
        //public string City { get; set; }
        //public string ZIPCode { get; set; }
    }
}
